#
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#

#--------------
# Service
#--------------
service:
  threads:
    min: 5
    max: 50
  topics:
    cashback: cashback-credit

#--------------
# Spring
#--------------
spring:
  application:
    name: salesservice

  # Profiles
  profiles:
    active:

  # i18n
  messages:
    basename: messages
    messages:
      encoding: UTF-8

  # MVC
  mvc:
    favicon:
      enabled: false

  # Data
  data:
    mongodb:
      database: db-sales
      host: ${MONGO_SERVERS:localhost}

  # Kafka CashbackCreditProducer
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

#--------------
# Logging
#--------------
logging:

#--------------
# HTTP Server
#--------------
server:
  port: 8080

#--------------
# Migrations
#--------------
mongobee:
  enabled: true
  scan: com.viniland.sales.persistence.changelog
  collections:
    changes: change_logs
    locks: change_locks



#--------------
# Spotify
#--------------
spotify:
  id: ${SPOTIFY_CLIENT_ID}
  secret: ${SPOTIFY_CLIENT_SECRET}

#--------------
# JWT
#   see http://www.allkeysgenerator.com
#   see https://jwt.io/
#--------------
jwt:
  secret: SgUkXp2s5v8y/B?E(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-K
  auth: /api/auth
  claims:
    iss: sales-service

#--------------
# Springfox
#--------------
springfox:
  documentation:
    swagger:
      v2:
        path: /v1.0/api-docs



